[package]
name = "wallshift"
version = "0.2.5"
edition = "2021"
authors = ["Yago Iglesias Vazquez  <yago.iglesias.vazquez@gmail.com>"]
description = " Simple wallpaper updater using feh"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/Yag000/wallshift"
repository = "https://github.com/Yag000/wallshift"
documentation = "https://github.com/Yag000/wallshift"
keywords = ["wallpaper", "wallpaper-changer"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
clap_derive = "4.5.4"
config = "0.14.0"
daemonize = "0.5.0"
home = "0.5.9"
rand = "0.8.5"
serde = "1.0.200"
serde_derive = "1.0.188"
thiserror = "1.0.59"
